DOC-4130
couchbase/docs-sdk-nodejs pull request #1
Opened 2018-09-27 18:17 UTC by RichardSmedley

2018-10-01 07:27 UTC, brett19 requested changes
Just some minor linking failures during the conversion.

2018-10-01 07:27 UTC, brett19 commented on modules/ROOT/pages/relnotes-nodejs-sdk.adoc
> +* http://issues.couchbase.com/browse/JSCBC-342[JSCBC-3]http://issues.couchbase.com/browse/JSCBC-395[95]:
The linking here is a little bit broken I think.

2018-10-01 07:27 UTC, brett19 commented on modules/ROOT/pages/relnotes-nodejs-sdk.adoc
> +* http://issues.couchbase.com/browse/JSCBC-358[JSCBC-3]http://issues.couchbase.com/browse/JSCBC-371[71]:
Here too!

2018-10-01 07:27 UTC, brett19 commented on modules/ROOT/pages/relnotes-nodejs-sdk.adoc
> +* http://issues.couchbase.com/browse/JSCBC-352[JSCBC-3]http://issues.couchbase.com/browse/JSCBC-361[61]:
Woopsies.

2018-10-01 07:27 UTC, brett19 commented on modules/ROOT/pages/relnotes-nodejs-sdk.adoc
> +* http://issues.couchbase.com/browse/JSCBC-339[JSCBC-3]http://issues.couchbase.com/browse/JSCBC-340[40]:
I'll stop now.

2018-10-01 07:34 UTC, RichardSmedley commented
Changes made

2018-10-02 19:08 UTC, brett19 commented
+1

2018-10-02 19:29 UTC, merged